services:
  node:
    image: ghcr.io/jrochub/power_house:0.3.20
    build: .
    command:
      [
        "net", "start",
        "--node-id", "node3",
        "--log-dir", "/data/logs",
        "--blob-dir", "/data/blob",
        "--listen", "/ip4/0.0.0.0/tcp/7003",
        "--broadcast-interval", "1500",
        "--quorum", "1",
        "--key", "ed25519://docker-node3",
        "--evm-chain-id", "177155",
        "--evm-rpc-listen", "0.0.0.0:8545",
        "--metrics", ":9100"
      ]
    ports:
      - "7003:7003"
      - "8545:8545"
      - "9103:9100"
    volumes:
      - ./docker/node3:/data
