[package]
name = "power-house-sfcs-conformance-guest"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
risc0-zkvm = { version = "3.0.6", default-features = false }

[[bin]]
name = "power-house-sfcs-conformance-guest"
path = "src/main.rs"

[[bin]]
name = "power-house-sfcs-general-guest"
path = "src/general.rs"
